
version: "3"
services:
  pgdatabase:
    image: postgres:13
    container_name: db
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    # volumes:
    #   - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "postgres"]
      interval: 5s
      retries: 5

# volumes:
#   postgres-db-volume: